spring.config.activate.on-profile=dev
server.port = 8081

jwt.secret=${JWT_SECRET}

spring.datasource.driver-class-name=${DEV_DB_DRIVER}
spring.datasource.url=${DEV_DB_URL}
spring.datasource.username=${DEV_DB_USERNAME}
spring.datasource.password=${DEV_DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop

CLOUDINARY_URL=${CLOUDINARY_URL}

whatsapp.api.base-url=${WHATSAPP_API_BASE_URL}
whatsapp.company.access-token=${WHATSAPP_COMPANY_ACCESS_TOKEN}
whatsapp.company.phone-id=${WHATSAPP_COMPANY_PHONE_ID}
whatsapp.webhook.verify-token=${WHATSAPP_WEBHOOK_VERIFY_TOKEN}

#logging.level.org.springframework.security=DEBUG
